language: python
python:
  - 2.6
  - 2.7
script: make travis
install:
  - pip install nose
  - pip install pep8
  - pip install pyflakes
  - pip install coverage
  - pip install mock
  - pip install . --use-mirrors
